language: csharp
dist: bionic
mono: none
dotnet: 3.1.100

script:
  - dotnet build
  - dotnet test tests/unit/microwf.UnitTests.csproj
  - dotnet test tests/integration/microwf.IntegrationTests.csproj