name: deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        VERSION=${{ github.event.release.tag_name }}
        echo "VERSION=${VERSION:1}" >> $GITHUB_ENV
    - name: Echo VERSION
      run: |
        echo $VERSION
        echo ${{ env.VERSION }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Pack
      run: ./build.sh "pack --version=$VERSION"
    - name: Push
      run:  dotnet nuget push .\artifacts\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET }}