name: deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        echo "RELEASE_VERSION=${RELEASE_VERSION:1}" >> $GITHUB_ENV
    - name: Echo RELEASE_VERSION
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Pack
      run: ./build.sh "pack --version=3.1.1"
    - name: Push
      run:  dotnet nuget push ./artifacts/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET }}
